#!/bin/bash

set -euxv

std_build_tools=(
	meson gcc gcc-c++
)
std_build_deps=(
	glib2-devel libusb1-devel
)
extra_deps=(
	# used to download and unpack validity binaries
	tar rpm cpio wget
)

yum -y install "${std_build_tools[@]}" "${std_build_deps[@]}" "${extra_deps[@]}"

mkdir /tmp/validity-binaries
cd /tmp/validity-binaries
wget https://ftp.hp.com/pub/softpaq/sp84501-85000/sp84530.tar -O - | tar xf -
rpm2cpio SP*/*.rpm | cpio -idmv
